MRCD8-218 added visual indicators for meatballs and arrows
SU-HSDO/stanford_mrc pull request #78
Opened 2018-02-27 00:05 UTC by josephgknox

# READY FOR REVIEW

# Summary
- Added visual indicators for focus on meatballs below slideshow and to arrows that overlay images

# Needed By (Date)
- End of sprint (3/1)

# Urgency
- N/A

# Steps to Test

1. Pull this branch
2. Ensure that the focus state for the meatballs and the previous and next buttons now have focus states (leveraging the Decanter $focus-shadow variable)

# Affected Projects or Products
- MRC
- stanford_mrc

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/MRCD8-218

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2018-02-27 00:49 UTC, pookmish requested changes
I think it needs a much stronger effect than a box shadow for visually impaired users. Even i had a hard time telling where my focus was

2018-02-27 00:50 UTC, pookmish commented
And in fact we need complete focus styling for the entire site.

2018-02-28 20:02 UTC, pookmish commented on themes/math_research_center/scss/paragraph/mrc_slideshow.scss
> +        box-shadow: $focus-shadow;
So do we need these now that we have the mixin?

2018-02-28 20:11 UTC, josephgknox commented
@pookmish nope -- they're gone! :)

2018-02-28 20:34 UTC, pookmish commented
Still getting ```a:focus {
    outline: 0;
}```
that overrides that mixin.

2018-02-28 21:28 UTC, merged